version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/app
